[build]
  publish = "dist"
  command = "npm run build"
[build.environment]
  NODE_VERSION = "24"

[[redirects]]
  from = "/courses"
  to = "/archive"
  status = 301

[[redirects]]
  from = "/media"
  to = "/archive"
  status = 301
